### ISSUE TITLE
MediaRouter is not updated if new receiver comes online

### ISSUE THREAD

**Issue by giladna** [googlecodelabs/cast-videos-android#6]
If I have 2 TVs with CC
one is ON second is OFF

when clicking on CC icon the online receiver is detected
when turning on the other TV
and CC becomes online, then click on CC icon 
the device does not appear in the list
going to BG and back fixed the problem 

Even when using the offical Cast APP in the play store the device is not discovered when coming online until I go to background and come back

10x
Gilad.

**Comment by entertailion** [comment]
You can file a bug against the SDK: https://code.google.com/p/google-cast-sdk/issues/list
